[package]
name = "platinum"
version = "0.1.0"
edition = "2021"

[dependencies]
v8 = "0.60.0"
tokio = { version = "1", features = ["full"] }
clearscreen = "1.0.10"
gethostname = "0.4.1"
cpuid = "0.1.1"